import React from 'react';
import './CreateTodoButton.css';

function CreateTodoButton({ todos, setTodos }) {

    const createTodo = (msg) => {
        alert(msg);
        todos.push({id:'hashAutogenerated', text:'This one is a new todo', completed: false});
        setTodos(todos);
    };

    return (
        <button className='create-todo-button' onClick={ () => createTodo('Aquí debería abrise un modal') }>+</button>
    );
}

export { CreateTodoButton }